import type { Race } from './combat';

/** Which AI / body an archetype uses. */
export type EnemyAi =
  | 'brawler' | 'lily' | 'panarms' | 'hidoom' | 'migium' | 'gunbot' | 'garanz' | 'sinow' | 'node' | 'mite' | 'drone'
  | 'dimenian' | 'delsaber' | 'sorcerer' | 'belra' | 'bringer';

/** Statuses enemy attacks can put on the player (Corruption: the Ruins, max HP lost per stack). */
export type PlayerStatus = 'poison' | 'paralysis' | 'burn' | 'corrupt';

export interface EnemyArchetype {
  name: string;
  ai: EnemyAi;
  color: number;
  scale: number;
  race: Race;
  hp: number;
  atp: number;
  dfp: number;
  ata: number;
  evp: number;
  moveSpeed: number;
  turnSpeed: number;
  aggroRange: number;
  attackRange: number;
  strikeRange: number;
  strikeArcDeg: number;
  windup: number;
  strikeActive: number;
  recovery: number;
  /** Number of strikes per attack (follow-ups use a short re-windup). */
  strikes: number;
  /** Random extra delay before deciding to attack again. */
  attackCooldown: number;
  /** Stagger points that make it flinch (a normal melee hit adds 1; see `stagger`). */
  poise: number;
  hitstun: number;
  lunge: number; // forward distance covered during the strike
  /** Knockback of a landed strike (defaults to the player's standard hit knockback). */
  strikeKnockback?: number;
  xp: number;
  meseta: [number, number];
  dropRate: number; // chance of any drop
  rareRate: number; // chance a drop is a rare
  /** Max item tier this enemy drops. */
  dropTier: number;
  /** Rares this enemy can drop (defaults to the Forest pool). */
  rarePool?: string[];
  /** Ranged / caster attacks: seconds between attacks, reach, telegraph time and blast radius. */
  shotCooldown?: number;
  shotRange?: number;
  shotWindup?: number;
  shotRadius?: number;
  /** Status the ranged attack inflicts, and its chance. */
  shotStatus?: PlayerStatus;
  shotStatusChance?: number;
  /** Status a landed melee strike inflicts, and its chance (its windup glows violet when it corrupts). */
  strikeStatus?: PlayerStatus;
  strikeStatusChance?: number;
}

export type EnemyId =
  | 'Booma' | 'Gobooma' | 'Gigobooma'
  | 'CaveBooma' | 'CaveGobooma' | 'CaveGigobooma'
  | 'PoisonLily' | 'NarLily'
  | 'PanArms' | 'Hidoom' | 'Migium'
  | 'Gillchic' | 'Garanz' | 'Sinow' | 'ControlNode'
  | 'SparkMite' | 'RepairDrone'
  | 'Dimenian' | 'LaDimenian' | 'SoDimenian' | 'Delsaber' | 'ChaosSorcerer' | 'DarkBelra' | 'ChaosBringer';

const CAVE_RARES = ['lily_sting', 'spread_needle', 'coral_rod', 'red_saber', 'varista', 'club_of_laconium', 'flowens_sword'];
/** Mines enemies drop from the cave rare pool too (the Warden carries its own signature drops). */
const MINE_RARES = ['lily_sting', 'spread_needle', 'coral_rod', 'rol_lance', 'flowens_sword', 'dragon_slayer'];
/** Ruins enemies: the Ruins rares, plus the older ones (Dark Falz carries its own signature drops). */
const RUIN_RARES = ['brionac', 'holy_ray', 'psycho_wand', 'rol_lance', 'lily_sting', 'spread_needle'];

export const enemies: Record<EnemyId, EnemyArchetype> = {
  Booma: {
    name: 'Booma',
    ai: 'brawler',
    color: 0x8a5a2b,
    scale: 1.0,
    race: 'native',
    hp: 75,
    atp: 70,
    dfp: 10,
    ata: 80,
    evp: 40,
    moveSpeed: 2.4,
    turnSpeed: 4,
    aggroRange: 18,
    attackRange: 1.9,
    strikeRange: 2.3,
    strikeArcDeg: 100,
    windup: 0.98,
    strikeActive: 0.18,
    recovery: 1.08,
    strikes: 1,
    attackCooldown: 1.04,
    poise: 1,
    hitstun: 0.46,
    lunge: 0.8,
    xp: 8,
    meseta: [8, 20],
    dropRate: 0.35,
    rareRate: 0.006,
    dropTier: 1,
  },
  Gobooma: {
    name: 'Gobooma',
    ai: 'brawler',
    color: 0x3f6b8a,
    scale: 1.12,
    race: 'native',
    hp: 120,
    atp: 95,
    dfp: 18,
    ata: 90,
    evp: 50,
    moveSpeed: 2.62,
    turnSpeed: 4.4,
    aggroRange: 18,
    attackRange: 2.0,
    strikeRange: 2.5,
    strikeArcDeg: 110,
    windup: 0.85,
    strikeActive: 0.18,
    recovery: 0.96,
    strikes: 1,
    attackCooldown: 0.78,
    poise: 2,
    hitstun: 0.4,
    lunge: 1.0,
    xp: 14,
    meseta: [15, 35],
    dropRate: 0.42,
    rareRate: 0.012,
    dropTier: 2,
  },
  Gigobooma: {
    name: 'Gigobooma',
    ai: 'brawler',
    color: 0x6a2f7a,
    scale: 1.25,
    race: 'native',
    hp: 190,
    atp: 125,
    dfp: 26,
    ata: 100,
    evp: 60,
    moveSpeed: 2.92,
    turnSpeed: 4.8,
    aggroRange: 20,
    attackRange: 2.2,
    strikeRange: 2.8,
    strikeArcDeg: 120,
    windup: 0.72,
    strikeActive: 0.22,
    recovery: 1.02,
    strikes: 2,
    attackCooldown: 0.65,
    poise: 3,
    hitstun: 0.34,
    lunge: 1.3,
    xp: 22,
    meseta: [25, 60],
    dropRate: 0.5,
    rareRate: 0.025,
    dropTier: 2,
  },

  // ---- Caves (tuned for Lv 12-22) ----
  // The Booma family in cave colours: tougher hides, harder hits, a touch faster.
  CaveBooma: {
    name: 'Cave Booma',
    ai: 'brawler',
    color: 0xa8442a,
    scale: 1.04,
    race: 'abeast',
    hp: 160,
    atp: 140,
    dfp: 30,
    ata: 108,
    evp: 65,
    moveSpeed: 2.6,
    turnSpeed: 4.4,
    aggroRange: 18,
    attackRange: 1.9,
    strikeRange: 2.4,
    strikeArcDeg: 105,
    windup: 0.88,
    strikeActive: 0.18,
    recovery: 1.0,
    strikes: 1,
    attackCooldown: 0.9,
    poise: 1,
    hitstun: 0.42,
    lunge: 0.9,
    xp: 40,
    meseta: [30, 70],
    dropRate: 0.4,
    rareRate: 0.01,
    dropTier: 4,
    rarePool: CAVE_RARES,
  },
  CaveGobooma: {
    name: 'Cave Gobooma',
    ai: 'brawler',
    color: 0x2f5a6a,
    scale: 1.15,
    race: 'abeast',
    hp: 250,
    atp: 160,
    dfp: 40,
    ata: 118,
    evp: 75,
    moveSpeed: 2.8,
    turnSpeed: 4.6,
    aggroRange: 18,
    attackRange: 2.0,
    strikeRange: 2.6,
    strikeArcDeg: 115,
    windup: 0.78,
    strikeActive: 0.18,
    recovery: 0.92,
    strikes: 1,
    attackCooldown: 0.7,
    poise: 2,
    hitstun: 0.38,
    lunge: 1.1,
    xp: 60,
    meseta: [45, 95],
    dropRate: 0.45,
    rareRate: 0.016,
    dropTier: 4,
    rarePool: CAVE_RARES,
  },
  CaveGigobooma: {
    name: 'Cave Gigobooma',
    ai: 'brawler',
    color: 0x5a5a62,
    scale: 1.28,
    race: 'abeast',
    hp: 360,
    atp: 180,
    dfp: 50,
    ata: 128,
    evp: 85,
    moveSpeed: 3.0,
    turnSpeed: 5,
    aggroRange: 20,
    attackRange: 2.2,
    strikeRange: 2.9,
    strikeArcDeg: 125,
    windup: 0.68,
    strikeActive: 0.22,
    recovery: 0.98,
    strikes: 2,
    attackCooldown: 0.6,
    poise: 3,
    hitstun: 0.32,
    lunge: 1.4,
    xp: 90,
    meseta: [60, 130],
    dropRate: 0.55,
    rareRate: 0.03,
    dropTier: 5,
    rarePool: CAVE_RARES,
  },
  // Rooted plant: spits an arcing poison glob at range, bursts its petals if you stand next to it.
  PoisonLily: {
    name: 'Poison Lily',
    ai: 'lily',
    color: 0x6a9a3a,
    scale: 1.0,
    race: 'native',
    hp: 120,
    atp: 150,
    dfp: 25,
    ata: 112,
    evp: 45,
    moveSpeed: 0,
    turnSpeed: 3,
    aggroRange: 17,
    attackRange: 2.6, // petal burst
    strikeRange: 3.0,
    strikeArcDeg: 360,
    windup: 0.75,
    strikeActive: 0.15,
    recovery: 0.9,
    strikes: 1,
    attackCooldown: 1.2,
    poise: 1,
    hitstun: 0.4,
    lunge: 0,
    xp: 45,
    meseta: [30, 70],
    dropRate: 0.45,
    rareRate: 0.012,
    dropTier: 4,
    rarePool: ['lily_sting', 'spread_needle'],
    shotCooldown: 3.6,
    shotRange: 16,
    shotWindup: 1.25,
    shotRadius: 1.7,
    shotStatus: 'poison',
    shotStatusChance: 1,
  },
  // Rare red Lily: paralysing spit, sturdier, much better drops.
  NarLily: {
    name: 'Nar Lily',
    ai: 'lily',
    color: 0xc0303a,
    scale: 1.12,
    race: 'native',
    hp: 280,
    atp: 170,
    dfp: 35,
    ata: 125,
    evp: 55,
    moveSpeed: 0,
    turnSpeed: 3.4,
    aggroRange: 18,
    attackRange: 2.8,
    strikeRange: 3.2,
    strikeArcDeg: 360,
    windup: 0.7,
    strikeActive: 0.15,
    recovery: 0.8,
    strikes: 1,
    attackCooldown: 1,
    poise: 2,
    hitstun: 0.35,
    lunge: 0,
    xp: 160,
    meseta: [150, 300],
    dropRate: 1,
    rareRate: 0.2,
    dropTier: 5,
    rarePool: ['lily_sting', 'spread_needle', 'coral_rod'],
    shotCooldown: 3.2,
    shotRange: 17,
    shotWindup: 1.15,
    shotRadius: 1.9,
    shotStatus: 'paralysis',
    shotStatusChance: 0.7,
  },
  // Slow brute with a wide two-armed slam; splits into Hidoom + Migium at half HP.
  PanArms: {
    name: 'Pan Arms',
    ai: 'panarms',
    color: 0x5a4a8a,
    scale: 1.0,
    race: 'abeast',
    hp: 560,
    atp: 190,
    dfp: 48,
    ata: 120,
    evp: 50,
    moveSpeed: 1.7,
    turnSpeed: 2.6,
    aggroRange: 20,
    attackRange: 2.8,
    strikeRange: 3.5,
    strikeArcDeg: 170,
    windup: 1.3,
    strikeActive: 0.22,
    recovery: 1.5,
    strikes: 1,
    attackCooldown: 1.2,
    poise: 5,
    hitstun: 0.3,
    lunge: 0.6,
    strikeKnockback: 11,
    xp: 0, // the halves carry the reward
    meseta: [0, 0],
    dropRate: 0,
    rareRate: 0,
    dropTier: 4,
  },
  // Red half: fast three-swipe claw flurry.
  Hidoom: {
    name: 'Hidoom',
    ai: 'hidoom',
    color: 0xb03a3a,
    scale: 1.0,
    race: 'abeast',
    hp: 200,
    atp: 160,
    dfp: 38,
    ata: 125,
    evp: 80,
    moveSpeed: 3.5,
    turnSpeed: 6,
    aggroRange: 22,
    attackRange: 1.9,
    strikeRange: 2.3,
    strikeArcDeg: 110,
    windup: 0.55,
    strikeActive: 0.12,
    recovery: 1.1,
    strikes: 3,
    attackCooldown: 0.8,
    poise: 1,
    hitstun: 0.35,
    lunge: 0.7,
    xp: 85,
    meseta: [60, 120],
    dropRate: 0.55,
    rareRate: 0.025,
    dropTier: 5,
    rarePool: CAVE_RARES,
  },
  // Blue half: keeps its distance and calls down paralysing lightning.
  Migium: {
    name: 'Migium',
    ai: 'migium',
    color: 0x3a5ab0,
    scale: 1.0,
    race: 'abeast',
    hp: 200,
    atp: 175,
    dfp: 38,
    ata: 120,
    evp: 60,
    moveSpeed: 1.6,
    turnSpeed: 4,
    aggroRange: 22,
    attackRange: 0,
    strikeRange: 0,
    strikeArcDeg: 0,
    windup: 1,
    strikeActive: 0.1,
    recovery: 1,
    strikes: 1,
    attackCooldown: 1,
    poise: 1,
    hitstun: 0.35,
    lunge: 0,
    xp: 85,
    meseta: [60, 120],
    dropRate: 0.55,
    rareRate: 0.025,
    dropTier: 5,
    rarePool: CAVE_RARES,
    shotCooldown: 3.4,
    shotRange: 15,
    shotWindup: 1.35,
    shotRadius: 2.2,
    shotStatus: 'paralysis',
    shotStatusChance: 0.35,
  },

  // ---- Mines (tuned for Lv 22-32) ----
  // Walking gunbot: keeps its distance and fires a telegraphed line shot. In a room with a
  // control node it is linked to it: it reboots after "dying" until the node is destroyed.
  Gillchic: {
    name: 'Gillchic',
    ai: 'gunbot',
    color: 0x8a96a8,
    scale: 1.0,
    race: 'machine',
    hp: 340,
    atp: 255,
    dfp: 62,
    ata: 150,
    evp: 80,
    moveSpeed: 2.2,
    turnSpeed: 4,
    aggroRange: 20,
    attackRange: 1.9, // close-range arm swipe
    strikeRange: 2.4,
    strikeArcDeg: 110,
    windup: 1.1,
    strikeActive: 0.16,
    recovery: 0.9,
    strikes: 1,
    attackCooldown: 1,
    poise: 2,
    hitstun: 0.4,
    lunge: 0.6,
    xp: 85,
    meseta: [70, 140],
    dropRate: 0.42,
    rareRate: 0.012,
    dropTier: 6,
    rarePool: MINE_RARES,
    shotCooldown: 3.4,
    shotRange: 16,
    shotWindup: 1.35,
    shotRadius: 0.9, // half the width of the shot's lane
  },
  // Artillery tank: walks slowly, plants itself (it can't turn while planted) and fires a
  // missile barrage at where you were. Its missiles hit machines and power switches too.
  Garanz: {
    name: 'Garanz',
    ai: 'garanz',
    color: 0x6a7a5a,
    scale: 1.0,
    race: 'machine',
    hp: 720,
    atp: 280,
    dfp: 78,
    ata: 140,
    evp: 50,
    moveSpeed: 1.5,
    turnSpeed: 1.6,
    aggroRange: 22,
    attackRange: 2.8, // stomp when you crowd it while it is walking
    strikeRange: 3.0,
    strikeArcDeg: 360,
    windup: 0.95,
    strikeActive: 0.15,
    recovery: 1.1,
    strikes: 1,
    attackCooldown: 1.4,
    poise: 5,
    hitstun: 0.3,
    lunge: 0,
    strikeKnockback: 10,
    xp: 160,
    meseta: [120, 240],
    dropRate: 0.6,
    rareRate: 0.03,
    dropTier: 6,
    rarePool: MINE_RARES,
    shotCooldown: 4.5,
    shotRange: 20,
    shotWindup: 1.25,
    shotRadius: 1.8,
    shotStatus: 'burn',
    shotStatusChance: 0.35,
  },
  // Ninja robot: leaps in with a quick three-hit combo (the last one burns), then
  // backflips away and lands in a short recovery: the punish window. Comes in pairs.
  Sinow: {
    name: 'Sinow Beat',
    ai: 'sinow',
    color: 0x5a6aa0,
    scale: 1.0,
    race: 'machine',
    hp: 420,
    atp: 260,
    dfp: 58,
    ata: 165,
    evp: 120,
    moveSpeed: 3.6,
    turnSpeed: 7,
    aggroRange: 22,
    attackRange: 9, // starts a leap from here
    strikeRange: 2.5,
    strikeArcDeg: 120,
    windup: 0.9, // crouch before the leap (and before a close-range combo)
    strikeActive: 0.12,
    recovery: 1.25, // after the backflip landing
    strikes: 3,
    attackCooldown: 1.6,
    poise: 2,
    hitstun: 0.35,
    lunge: 0.5,
    xp: 115,
    meseta: [90, 170],
    dropRate: 0.5,
    rareRate: 0.02,
    dropTier: 6,
    rarePool: MINE_RARES,
  },
  // The room's control node: a pylon that keeps linked gunbots rebooting. No attacks.
  ControlNode: {
    name: 'Control Node',
    ai: 'node',
    color: 0x40c0ff,
    scale: 1.0,
    race: 'machine',
    hp: 520,
    atp: 0,
    dfp: 70,
    ata: 0,
    evp: 20,
    moveSpeed: 0,
    turnSpeed: 0,
    aggroRange: 0,
    attackRange: 0,
    strikeRange: 0,
    strikeArcDeg: 0,
    windup: 1,
    strikeActive: 0.1,
    recovery: 1,
    strikes: 1,
    attackCooldown: 1,
    poise: 3,
    hitstun: 0.3,
    lunge: 0,
    xp: 120,
    meseta: [100, 200],
    dropRate: 0.8,
    rareRate: 0.02,
    dropTier: 6,
    rarePool: MINE_RARES,
  },
  // ---- The Warden's adds (summoned in its fight, never in waves; they give nothing) ----
  // Scuttles at you, squats and arms a small burning blast (strikeRange is its radius, windup its fuse).
  SparkMite: {
    name: 'Spark Mite',
    ai: 'mite',
    color: 0x8a7a68,
    scale: 0.6,
    race: 'machine',
    hp: 70,
    atp: 270,
    dfp: 30,
    ata: 160,
    evp: 50,
    moveSpeed: 3.7,
    turnSpeed: 8,
    aggroRange: 40,
    attackRange: 1.8,
    strikeRange: 2.4,
    strikeArcDeg: 360,
    windup: 1.0,
    strikeActive: 0.1,
    recovery: 0.5,
    strikes: 1,
    attackCooldown: 1,
    poise: 1,
    hitstun: 0.35,
    lunge: 0,
    xp: 0,
    meseta: [0, 0],
    dropRate: 0,
    rareRate: 0,
    dropTier: 6,
  },
  // Flies to a post by the alcove and beams repairs into the Warden's core until shot down.
  RepairDrone: {
    name: 'Repair Drone',
    ai: 'drone',
    color: 0x6a90a8,
    scale: 0.9,
    race: 'machine',
    hp: 160,
    atp: 0,
    dfp: 45,
    ata: 0,
    evp: 90,
    moveSpeed: 3.2,
    turnSpeed: 4,
    aggroRange: 0,
    attackRange: 0,
    strikeRange: 0,
    strikeArcDeg: 0,
    windup: 1,
    strikeActive: 0.1,
    recovery: 1,
    strikes: 1,
    attackCooldown: 1,
    poise: 2,
    hitstun: 0.45,
    lunge: 0,
    xp: 0,
    meseta: [0, 0],
    dropRate: 0,
    rareRate: 0,
    dropTier: 6,
  },

  // ---- Ruins (tuned for Lv 32-42; all Dark) ----
  // The Dimenian family: sword-carrying grunts in packs. Each step up adds a cut to the chain;
  // the gold So Dimenian's cuts corrupt (its windup glows violet).
  Dimenian: {
    name: 'Dimenian',
    ai: 'dimenian',
    color: 0x4a5ad0,
    scale: 1.0,
    race: 'dark',
    hp: 350,
    atp: 270,
    dfp: 72,
    ata: 172,
    evp: 100,
    moveSpeed: 3.0,
    turnSpeed: 5,
    aggroRange: 20,
    attackRange: 2.0,
    strikeRange: 2.5,
    strikeArcDeg: 110,
    windup: 0.9,
    strikeActive: 0.16,
    recovery: 0.95,
    strikes: 1,
    attackCooldown: 1,
    poise: 2,
    hitstun: 0.38,
    lunge: 0.9,
    xp: 120,
    meseta: [90, 180],
    dropRate: 0.42,
    rareRate: 0.012,
    dropTier: 7,
    rarePool: RUIN_RARES,
  },
  LaDimenian: {
    name: 'La Dimenian',
    ai: 'dimenian',
    color: 0xc0383e,
    scale: 1.05,
    race: 'dark',
    hp: 425,
    atp: 290,
    dfp: 80,
    ata: 180,
    evp: 108,
    moveSpeed: 3.2,
    turnSpeed: 5.4,
    aggroRange: 20,
    attackRange: 2.1,
    strikeRange: 2.6,
    strikeArcDeg: 115,
    windup: 0.85,
    strikeActive: 0.16,
    recovery: 0.95,
    strikes: 2,
    attackCooldown: 0.95,
    poise: 2,
    hitstun: 0.36,
    lunge: 1.0,
    xp: 150,
    meseta: [110, 210],
    dropRate: 0.45,
    rareRate: 0.016,
    dropTier: 7,
    rarePool: RUIN_RARES,
  },
  SoDimenian: {
    name: 'So Dimenian',
    ai: 'dimenian',
    color: 0xd8a830,
    scale: 1.1,
    race: 'dark',
    hp: 515,
    atp: 315,
    dfp: 90,
    ata: 188,
    evp: 115,
    moveSpeed: 3.3,
    turnSpeed: 5.6,
    aggroRange: 22,
    attackRange: 2.2,
    strikeRange: 2.7,
    strikeArcDeg: 120,
    windup: 0.82,
    strikeActive: 0.18,
    recovery: 1.05,
    strikes: 3,
    attackCooldown: 0.9,
    poise: 3,
    hitstun: 0.34,
    lunge: 1.1,
    xp: 185,
    meseta: [130, 250],
    dropRate: 0.5,
    rareRate: 0.025,
    dropTier: 7,
    rarePool: RUIN_RARES,
    strikeStatus: 'corrupt',
    strikeStatusChance: 0.5,
  },
  // Shield knight: its guard blocks light hits from the front (a heavy hit breaks it and staggers it).
  // Leaps in from attackRange with a three-cut combo (the crouch is its windup).
  Delsaber: {
    name: 'Delsaber',
    ai: 'delsaber',
    color: 0x3a4a6a,
    scale: 1.0,
    race: 'dark',
    hp: 590,
    atp: 305,
    dfp: 95,
    ata: 185,
    evp: 95,
    moveSpeed: 2.6,
    turnSpeed: 4.5,
    aggroRange: 22,
    attackRange: 7.5,
    strikeRange: 2.7,
    strikeArcDeg: 120,
    windup: 0.95,
    strikeActive: 0.14,
    recovery: 1.25,
    strikes: 3,
    attackCooldown: 1.5,
    poise: 3,
    hitstun: 0.36,
    lunge: 0.45,
    xp: 210,
    meseta: [140, 260],
    dropRate: 0.55,
    rareRate: 0.025,
    dropTier: 7,
    rarePool: RUIN_RARES,
  },
  // Floating caster: keeps its distance, blinks away when you close in, casts corrupting Gi-techs
  // (a fire ring around you, a lightning field, an ice line) and snuffs out lit pylons.
  ChaosSorcerer: {
    name: 'Chaos Sorcerer',
    ai: 'sorcerer',
    color: 0x6a2a8a,
    scale: 1.0,
    race: 'dark',
    hp: 440,
    atp: 315,
    dfp: 70,
    ata: 190,
    evp: 125,
    moveSpeed: 2.2,
    turnSpeed: 5,
    aggroRange: 22,
    attackRange: 0,
    strikeRange: 0,
    strikeArcDeg: 0,
    windup: 1,
    strikeActive: 0.1,
    recovery: 1.1,
    strikes: 1,
    attackCooldown: 1.2,
    poise: 2,
    hitstun: 0.4,
    lunge: 0,
    xp: 200,
    meseta: [140, 260],
    dropRate: 0.55,
    rareRate: 0.025,
    dropTier: 7,
    rarePool: RUIN_RARES,
    shotCooldown: 3.8,
    shotRange: 18,
    shotWindup: 1.3,
    shotRadius: 1.8,
    shotStatus: 'corrupt',
    shotStatusChance: 1,
  },
  // Slow giant: a long-reach rock punch down a lane, and a corrupting ground slam if you crowd it.
  DarkBelra: {
    name: 'Dark Belra',
    ai: 'belra',
    color: 0x5a3a7a,
    scale: 1.0,
    race: 'dark',
    hp: 950,
    atp: 360,
    dfp: 105,
    ata: 178,
    evp: 60,
    moveSpeed: 1.7,
    turnSpeed: 2.4,
    aggroRange: 22,
    attackRange: 3.0,
    strikeRange: 3.3,
    strikeArcDeg: 360,
    windup: 1.2,
    strikeActive: 0.2,
    recovery: 1.4,
    strikes: 1,
    attackCooldown: 1.3,
    poise: 6,
    hitstun: 0.3,
    lunge: 0,
    strikeKnockback: 11,
    xp: 300,
    meseta: [180, 340],
    dropRate: 0.65,
    rareRate: 0.035,
    dropTier: 7,
    rarePool: RUIN_RARES,
    shotCooldown: 4.2,
    shotRange: 11,
    shotWindup: 1.3,
    shotRadius: 0.95, // half the punch lane's width
    strikeStatus: 'corrupt',
    strikeStatusChance: 1,
  },
  // Centaur mini-boss (Ruin 2): charges down a lane across the room (the whole threat budget),
  // fires a fan of corrupting chest lasers, and stomps if you stand under it.
  ChaosBringer: {
    name: 'Chaos Bringer',
    ai: 'bringer',
    color: 0x2a2a3a,
    scale: 1.0,
    race: 'dark',
    hp: 1300,
    atp: 390,
    dfp: 110,
    ata: 186,
    evp: 70,
    moveSpeed: 2.5,
    turnSpeed: 2.2,
    aggroRange: 26,
    attackRange: 3.0,
    strikeRange: 3.1,
    strikeArcDeg: 360,
    windup: 0.95,
    strikeActive: 0.2,
    recovery: 1.6,
    strikes: 1,
    attackCooldown: 1.4,
    poise: 8,
    hitstun: 0.3,
    lunge: 0,
    strikeKnockback: 12,
    xp: 450,
    meseta: [220, 420],
    dropRate: 0.85,
    rareRate: 0.05,
    dropTier: 7,
    rarePool: RUIN_RARES,
    shotCooldown: 5,
    shotRange: 14,
    shotWindup: 1.2,
    shotRadius: 0.8, // half a laser's width
    shotStatus: 'corrupt',
    shotStatusChance: 1,
  },
};

/** Elite spawns (Caves, Mines): tougher, tinted, better rewards. */
export const elite = {
  chance: 1 / 12,
  hpMult: 1.6,
  atpMult: 1.25,
  xpMult: 2,
  /** Extra stagger points an elite needs before it flinches. */
  poiseBonus: 1,
};

/**
 * Elite affixes. Normal Mines elites roll Overclocked or Volatile; on Hard every elite (and
 * champion) rolls from the whole pool (see data/affixes.ts).
 */
export const affixes = {
  /** Overclocked: movement and attack speed (the total tempo is capped at tempoCap). */
  overclockedTempo: 1.5,
  tempoCap: 1.5,
  /** Overclocked: every attack is followed at once by one more; its windup is this share of the normal one. */
  followUpWindup: 0.6,
  /** Volatile death blast: radius, warning, damage (× the elite's ATP), Burn, and the burning ground it leaves. */
  volatileRadius: 3.8,
  volatileWindup: 1.3,
  volatileAtpMult: 0.9,
  volatileBurn: 3,
  volatileGroundLife: 4,
  /** Volatile vent: while you are within ventRange, a blast around itself every ventEvery s. */
  ventEvery: 4,
  ventRange: 3.6,
  ventRadius: 2.6,
  ventWindup: 0.9,
  ventAtpMult: 0.6,
  /** Shielding: allies within this range (up to shieldTargets) take shieldMult damage while it lives. */
  shieldRange: 8,
  shieldTargets: 3,
  shieldMult: 0.3,
  /** Shielding with nobody left to protect: damage from in front of it (within this half-arc) is cut this much. */
  selfShieldMult: 0.4,
  selfShieldArcDeg: 70,
  /** Shielding: how far behind its allies (away from you) it tries to stand. */
  shieldHangBack: 2.5,
  /** Regenerating: max HP healed per second, once it hasn't been hit for regenDelay s (Burn / Poison stop it). */
  regenPerSec: 0.04,
  regenDelay: 2,
  /** Regenerating: every regenPulseEvery s, allies within regenPulseRange heal this share of their max HP. */
  regenPulseEvery: 8,
  regenPulseRange: 6,
  regenPulseHeal: 0.12,
  /** Splitting: this many copies with this share of max HP each, smaller and faster. */
  splitCount: 3,
  splitHp: 0.35,
  splitScale: 0.72,
  splitSpeed: 1.3,
  /** Molten: a burning patch every moltenEvery seconds while it walks. */
  moltenEvery: 0.55,
  moltenRadius: 1.3,
  moltenLife: 6,
  /** Molten: where its attacks land burns too (patch radius for melee swings). */
  moltenStrikeRadius: 1.4,
  /** Molten: every spewEvery s in a fight it lobs spewGlobs globs that land as burning patches. */
  spewEvery: 4,
  spewGlobs: 2,
  spewWindup: 1.0,
  spewRadius: 1.4,
  spewAtpMult: 0.4,
  /** Stormcaller: every stormEvery s in combat, stormBolts circles near you (the second leads your movement). */
  stormEvery: 4.5,
  stormBolts: 3,
  stormWindup: 1.2,
  stormRadius: 1.5,
  stormAtpMult: 0.6,
  stormParalysis: 0.4,
  /** Frenzied: below this HP share it runs at frenzyTempo, can't be staggered and hits frenzyAtp harder. */
  frenzyAt: 0.4,
  frenzyTempo: 1.3,
  frenzyAtp: 1.3,
  frenzyScale: 1.1,
  /** The roar when it crosses the threshold: radius, damage (× ATP) and knockback. */
  roarRadius: 3.5,
  roarAtpMult: 0.3,
  roarKnockback: 10,
};
