import {
  arpPart, bassPart, compPart, hits, melody, padPart, progression, shift, walkingBass,
  type NoteEv, type Part,
} from './theory';

// Original tunes in the spirit of the PSO score. Each field track has a calm
// and a battle arrangement over the same chords and tempo; the sequencer
// crossfades between them when a room's gates close / open. Boss tracks use
// the battle layer for their enraged phase.

export type TrackId = 'pioneer2' | 'forest' | 'caves' | 'dragon' | 'derolle' | 'mines' | 'warden';

export interface Track {
  id: TrackId;
  name: string;
  desc: string;
  bpm: number;
  /** Off-beat 8ths are pushed late by this fraction of an 8th (0 = straight). */
  swing?: number;
  bars: number;
  parts: Part[];
  /** Overall level (tracks are balanced to sit at a similar loudness). */
  gain?: number;
  /**
   * Recorded loops (generated by `npm run music`, served from public/). When
   * set, these play instead of `parts`; the parts stay as the fallback if a
   * file fails to load. Without a battle file the calm loop plays throughout.
   * `boss`: the calm loop is the fight itself, so it plays at battle level
   * instead of the quieter ambient level.
   */
  files?: { calm: string; battle?: string; boss?: boolean };
}

const p = (inst: Part['inst'], layer: Part['layer'], notes: NoteEv[], gain = 1, pan = 0): Part => ({ inst, layer, notes, gain, pan });

/** Single hits at the start of the given bars (crashes). */
const onBars = (bars: number[], n = 60, v = 0.9): NoteEv[] => bars.map((b) => ({ s: b * 16, n, l: 1, v }));

// ------------------------------------------------------------ Pioneer 2

function pioneer2(): Track {
  const bars = 16;
  const prog = progression([
    'Fmaj9', 'Em7 A7', 'Dm9', 'Dm9 G13', 'Cmaj9', 'Am9', 'Dm9', 'G7sus4',
    'Bbmaj7', 'Am7', 'Dm9', 'G7sus4', 'Fmaj9', 'Em7 A7', 'Dm9 G13', 'Cmaj9',
  ]);
  const mel = melody(`
    A5 - G5 - E5 - - - | G5 - E5 - C#5 - E5 - | F5 - - E5 D5 - A4 - | C5 - D5 - E5 - F5 - |
    E5 - - - D5 - B4 - | C5 - - - . . E5 G5 | A5 - G5 - F5 - E5 - | D5 - - - - - . . |
    D5 - F5 - A5 - - - | G5 - E5 - C5 - - - | F5 - E5 - D5 - A4 - | G5 - - - F5 - - . |
    E5 - F5 - G5 - A5 - | B5 - G5 - G5 - E5 - | F5 - E5 - D5 - - B4 | C5 - - - - - . . |`, 2, 0.75);
  return {
    id: 'pioneer2',
    name: 'Pioneer 2',
    desc: 'Hub. Recorded (ElevenLabs): cosy fairy-tale fantasy, flute and pan pipes over acoustic guitar, harp, strings and soft pads.',
    bpm: 92,
    swing: 0.3,
    bars,
    files: { calm: 'music/pioneer2-calm.mp3' },
    parts: [
      p('epiano', 'base', compPart(prog, 'x---..x-----.... x---...x---..x-.', 55, 0.5), 1, -0.15),
      p('softbass', 'base', walkingBass(prog, 36, 0.7)),
      p('vibes', 'base', mel, 0.9, 0.15),
      p('pad', 'base', padPart(prog, 60, 0.3), 0.6),
      p('ride', 'base', hits('x...X.o.x...X.o.', bars), 1, 0.25),
      p('hat', 'base', hits('....x.......x...', bars), 0.6),
      p('rim', 'base', hits('............x... ..........o.x...', bars), 0.5, -0.2),
    ],
  };
}

// --------------------------------------------------------------- Forest

function forest(): Track {
  const bars = 16;
  const prog = progression([
    'Gmaj7', 'A', 'F#m7', 'Bm7', 'Gmaj7', 'A', 'Bm7', 'Bm7',
    'Em7', 'F#m7', 'Gmaj7', 'D/F#', 'Em7', 'A7sus4', 'Dmaj7', 'A7',
  ]);
  const mel = melody(`
    D5 - - E5 F#5 - A5 - | G5 - F#5 - E5 - - - | C#5 - D5 - E5 - A4 - | D5 - - - - - . . |
    D5 - - E5 F#5 - B5 - | A5 - G5 - F#5 - E5 - | F#5 - - D5 E5 - - C#5 | B4 - - - - - . . |
    G5 - - F#5 E5 - D5 - | C#5 - - D5 E5 - A5 - | B5 - A5 - F#5 - D5 - | A5 - - - F#5 - - . |
    G5 - F#5 - E5 - G5 - | F#5 - E5 - D5 - E5 - | F#5 - - - - - E5 D5 | E5 - - - C#5 - - . |`, 2, 0.8);
  return {
    id: 'forest',
    name: 'Forest',
    desc: 'Recorded (ElevenLabs): flute, harp, acoustic guitar and strings. Battle: horns and trumpets, pumping bass and a drum kit.',
    bpm: 104,
    bars,
    files: { calm: 'music/forest-calm.mp3', battle: 'music/forest-battle.mp3' },
    parts: [
      p('pad', 'base', padPart(prog, 57, 0.55)),
      // Calm
      p('softbass', 'calm', bassPart(prog, 'r-------r---5---', 38, 0.7)),
      p('harp', 'calm', arpPart(prog, [0, 1, 2, 3, 4, 3, 2, 1], 2, 62, 0.55), 1, 0.2),
      p('flute', 'calm', mel, 1, -0.1),
      p('shaker', 'calm', hits('..x...x...x...x.', bars), 0.6, 0.3),
      // Battle
      p('kick', 'battle', hits('X.....x...x.....', bars)),
      p('snare', 'battle', hits('....X.......X...', bars, 60, [], { every: 4, pattern: '....X.......X.XX' })),
      p('hat', 'battle', hits('x.o.x.o.x.o.x.oo', bars), 1, 0.25),
      p('tom', 'battle', hits('................', bars, 50, [55, 50, 45, 40], { every: 8, pattern: '........1.2.3.44' }), 0.8),
      p('crash', 'battle', onBars([0, 8]), 0.8, 0.2),
      p('pumpbass', 'battle', bassPart(prog, 'r-r-o-r-r-r-o-5-', 38, 0.8)),
      p('stab', 'battle', compPart(prog, 'X-....x-....x-..', 57, 0.65), 0.9, -0.2),
      p('brass', 'battle', mel, 1.1, 0.1),
      p('arp', 'battle', arpPart(prog, [0, 2, 1, 3, 2, 4, 3, 5], 1, 62, 0.5), 0.6, 0.35),
    ],
  };
}

// ---------------------------------------------------------------- Caves

function caves(): Track {
  const bars = 16;
  // D mixolydian with open sus2 / add9 voicings: echoing and exploratory
  // rather than gloomy.
  const prog = progression([
    'Dsus2', 'Dsus2', 'Cadd9', 'Dsus2', 'Gadd9', 'Asus4', 'Dsus2', 'Cadd9',
    'Em7', 'Em7', 'Gmaj7', 'Gmaj7', 'Bm7', 'Asus4', 'Gadd9', 'A',
  ]);
  const mel = melody(`
    A5 - - - E5 - - - | D5 - - - E5 - A4 - | G5 - - - E5 - D5 - | E5 - - - - - . . |
    D5 - - - B4 - D5 - | E5 - - - D5 - A4 - | B4 - - - A4 - D5 - | E5 - - - - - . . |
    B5 - - - G5 - - - | A5 - - - G5 - E5 - | F#5 - - - D5 - - - | B4 - - - D5 - F#5 - |
    A5 - - - F#5 - D5 - | E5 - - - D5 - - - | B4 - - - D5 - G5 - | E5 - - - C#5 - . . |`, 2, 0.75);
  return {
    id: 'caves',
    name: 'Caves',
    desc: 'Recorded (ElevenLabs): sci-fi synth-orchestral, warm pads, electric piano and strings over a laid-back electronic beat. Battle: driving synth bass, staccato strings, a synth lead.',
    bpm: 88,
    bars,
    files: { calm: 'music/caves-calm.mp3', battle: 'music/caves-battle.mp3' },
    parts: [
      p('darkpad', 'base', padPart(prog, 48, 0.6, 3)),
      p('softbass', 'base', bassPart(prog, 'r---------------', 36, 0.6), 0.8),
      // Calm
      p('bell', 'calm', mel, 1, 0.15),
      p('harp', 'calm', arpPart(prog, [0, 2, 4, 5], 4, 55, 0.35), 0.7, -0.3),
      // Battle: tension from the strings and bass pulse rather than a beat.
      p('taiko', 'battle', hits('x..o............', bars, 38), 0.35),
      p('strings', 'battle', arpPart(prog, [0, 1, 0, 2], 2, 48, 0.4), 0.6, -0.2),
      p('softbass', 'battle', bassPart(prog, 'r...r...r...r...', 36, 0.5), 0.6),
      p('choir', 'battle', padPart(prog, 60, 0.35, 3), 0.5, 0.2),
      p('lead', 'battle', shift(mel, -12), 0.55, 0.1),
    ],
  };
}

// --------------------------------------------------------------- Dragon

function dragon(): Track {
  const bars = 16;
  const prog = progression([
    'Dm', 'Dm', 'Bb', 'C', 'Dm', 'Dm', 'Gm', 'A',
    'Bb', 'C', 'Dm', 'Dm', 'Gm', 'Bb', 'Asus4', 'A',
  ]);
  const mel = melody(`
    D5! - - - A4 - D5 - | F5 - E5 - D5 - C5 - | D5 - - - F5 - - - | E5 - - - G5 - - - |
    A5! - - - - - G5 F5 | E5 - F5 - D5 - - - | Bb4 - D5 - G5 - F5 - | E5 - - - C#5 - - - |
    F5! - - - D5 - F5 - | G5 - - - E5 - C5 - | A5 - - - F5 - D5 - | A5 - Bb5 - A5 - F5 - |
    G5! - - - D5 - G5 - | F5 - - - D5 - Bb4 - | D5 - - - - - E5 - | C#5 - - - - - . . |`, 2, 0.85);
  return {
    id: 'dragon',
    name: 'Dragon',
    desc: 'Boss. Recorded (ElevenLabs): orchestral rock in D minor, brass theme, string ostinatos, wordless choir, timpani. Enraged adds string runs and taiko.',
    bpm: 138,
    gain: 0.7,
    bars,
    files: { calm: 'music/dragon-calm.mp3', battle: 'music/dragon-battle.mp3', boss: true },
    parts: [
      p('choir', 'base', padPart(prog, 57, 0.55)),
      p('strings', 'base', arpPart(prog, [0, 1, 2, 1], 2, 50, 0.55), 0.9, -0.2),
      p('pumpbass', 'base', bassPart(prog, 'r-r-r-r-o-r-r-5-', 38, 0.85)),
      p('timpani', 'base', bassPart(prog, 'r.......r.r.....', 38, 0.7), 0.8),
      p('brass', 'base', mel, 1.15, 0.1),
      p('kick', 'base', hits('X...X...X...X...', bars)),
      p('snare', 'base', hits('....X.......X...', bars, 60, [], { every: 4, pattern: '....X.......XXXX' })),
      p('hat', 'base', hits('x.x.x.x.x.x.x.x.', bars), 0.9, 0.25),
      p('tom', 'base', hits('................', bars, 50, [55, 50, 45, 40], { every: 8, pattern: '........1.2.3.4.' }), 0.8),
      p('crash', 'base', onBars([0, 4, 8, 12]), 0.8),
      // Enraged
      p('arp', 'battle', arpPart(prog, [0, 1, 2, 3, 4, 3, 2, 1], 1, 62, 0.5), 0.7, 0.3),
      p('taiko', 'battle', hits('X..X..X.X..X..X.', bars, 38), 0.8),
      p('ohat', 'battle', hits('..x...x...x...x.', bars), 0.7, -0.25),
    ],
  };
}

// ------------------------------------------------------------ De Rol Le

function derolle(): Track {
  const bars = 16;
  const prog = progression([
    'Em', 'F', 'Em', 'F', 'C', 'D', 'Em', 'B7',
    'Am', 'F', 'C', 'G', 'Am', 'F', 'B7', 'B7',
  ]);
  const mel = melody(`
    E5! - - - B4 - E5 - | F5 - - - A5 - - - | G5 - F5 - E5 - D5 - | C5 - - - - - . . |
    E5! - G5 - C6 - B5 - | A5 - - - F#5 - D5 - | E5 - - - G5 - B5 - | A5 - - - D#5 - - - |
    A5! - - - E5 - A5 - | C6 - - - A5 - F5 - | G5 - - - E5 - C5 - | D5 - - - B4 - D5 - |
    E5! - - - A5 - C6 - | A5 - - - F5 - C6 - | B5 - - - A5 - F#5 - | D#5 - - - - - . . |`, 2, 0.85);
  return {
    id: 'derolle',
    name: 'De Rol Le',
    desc: 'Boss. Recorded (ElevenLabs): tense orchestral rock in E phrygian, galloping bass, guitar riffs, staccato strings. Phase 2 adds choir and taiko.',
    bpm: 150,
    gain: 0.75,
    bars,
    files: { calm: 'music/derolle-calm.mp3', battle: 'music/derolle-battle.mp3', boss: true },
    parts: [
      p('strings', 'base', padPart(prog, 52, 0.5)),
      p('arp', 'base', arpPart(prog, [0, 1, 2, 1, 3, 2, 1, 2], 1, 64, 0.5), 0.75, 0.3),
      p('pumpbass', 'base', bassPart(prog, 'r.rrr.rrr.rrr.rr', 40, 0.8)),
      p('lead', 'base', mel, 1.2, -0.1),
      p('stab', 'base', compPart(prog, 'X-.X-.X-........', 52, 0.6), 0.85, -0.25),
      p('kick', 'base', hits('X..x..X...x..x..', bars)),
      p('snare', 'base', hits('....X.......X..o', bars, 60, [], { every: 4, pattern: '....X.......XXXX' })),
      p('hat', 'base', hits('x.xxx.xxx.xxx.xx', bars), 0.7, 0.25),
      p('tom', 'base', hits('................', bars, 50, [57, 52, 47, 43], { every: 8, pattern: '1.1.2.2.3.3.4.4.' }), 0.8),
      p('crash', 'base', onBars([0, 8]), 0.8),
      // Phase 2
      p('choir', 'battle', padPart(prog, 60, 0.6)),
      p('taiko', 'battle', hits('X.......X.X.....', bars, 40), 0.9),
      p('brass', 'battle', compPart(prog, 'X-------x-------', 52, 0.6, 3), 0.8),
    ],
  };
}

// ---------------------------------------------------------------- Mines

function mines(): Track {
  const bars = 16;
  // A mixolydian with sus voicings: busy machinery, but bright and forward-moving rather than grim.
  const prog = progression([
    'Asus2', 'G6', 'Asus2', 'Dadd9', 'Fmaj7', 'G6', 'Asus4', 'A',
    'Dadd9', 'E7sus4', 'F#m7', 'Dmaj7', 'Bm7', 'G6', 'Esus4', 'E',
  ]);
  const mel = melody(`
    E5 - - - A5 - - - | G5 - - - E5 - D5 - | E5 - - - B4 - C#5 - | D5 - - - - - . . |
    C5 - - - F5 - E5 - | D5 - - - G5 - - - | A5 - - - E5 - - - | C#5 - - - - - . . |
    F#5 - - - A5 - - - | G#5 - - - E5 - - - | A5 - - - C#6 - B5 - | A5 - - - F#5 - - - |
    D5 - - - F#5 - A5 - | B5 - - - G5 - - - | A5 - - - E5 - - - | G#5 - - - - - . . |`, 2, 0.75);
  return {
    id: 'mines',
    name: 'Mines',
    desc: 'Synth (no recording yet). Calm: beatless pads, electric piano and a slow harp pulse. Battle: pumping synth bass, an arpeggio, strings and brass hits over a light kit.',
    bpm: 112,
    bars,
    parts: [
      p('pad', 'base', padPart(prog, 52, 0.5)),
      p('softbass', 'base', bassPart(prog, 'r-------r-------', 33, 0.55), 0.7),
      // Calm: ambient, no beat and no lead.
      p('epiano', 'calm', compPart(prog, 'x-------....x---', 57, 0.4), 0.8, -0.2),
      p('harp', 'calm', arpPart(prog, [0, 2, 4, 2], 4, 60, 0.3), 0.6, 0.25),
      // Battle
      p('pumpbass', 'battle', bassPart(prog, 'r.rr.rr.r.rr.r5.', 33, 0.75)),
      p('arp', 'battle', arpPart(prog, [0, 1, 2, 3, 2, 1, 2, 4], 1, 64, 0.45), 0.6, 0.3),
      p('strings', 'battle', padPart(prog, 57, 0.4), 0.6, -0.2),
      p('stab', 'battle', compPart(prog, 'X-....X-..X-....', 57, 0.55), 0.7, -0.25),
      p('brass', 'battle', mel, 0.9, 0.1),
      p('kick', 'battle', hits('X.......X.......', bars), 0.8),
      p('snare', 'battle', hits('....x.......x...', bars), 0.6),
      p('hat', 'battle', hits('..x...x...x...x.', bars), 0.6, 0.25),
    ],
  };
}

// ---------------------------------------------------------------- Warden

function warden(): Track {
  const bars = 16;
  const prog = progression([
    'Em', 'C', 'G', 'D', 'Em', 'C', 'Am', 'B7',
    'C', 'D', 'G', 'Em', 'Am', 'C', 'Bsus4', 'B',
  ]);
  const mel = melody(`
    E5! - - - G5 - B5 - | C6 - - - B5 - G5 - | D6 - - - B5 - G5 - | A5 - - - F#5 - - - |
    G5! - - - E5 - G5 - | A5 - - - G5 - E5 - | C6 - - - A5 - E5 - | D#5 - - - - - . . |
    E5! - - - G5 - C6 - | D6 - - - A5 - F#5 - | G5 - - - B5 - D6 - | E6 - - - B5 - - - |
    C6! - - - A5 - E5 - | G5 - - - E5 - C5 - | B4 - - - E5 - F#5 - | D#5 - - - - - . . |`, 2, 0.85);
  return {
    id: 'warden',
    name: 'Warden',
    desc: 'Boss. Synth (no recording yet): driving synth-orchestral in E minor with a brass theme, pumping bass and string ostinatos. The rerouted phase adds choir, taiko and a fast arpeggio.',
    bpm: 144,
    gain: 0.75,
    bars,
    parts: [
      p('strings', 'base', arpPart(prog, [0, 1, 2, 1], 2, 52, 0.5), 0.85, -0.2),
      p('pad', 'base', padPart(prog, 55, 0.45), 0.7),
      p('pumpbass', 'base', bassPart(prog, 'r-r-r-r-o-r-r-5-', 40, 0.8)),
      p('brass', 'base', mel, 1.1, 0.1),
      p('kick', 'base', hits('X...X...X...X...', bars)),
      p('snare', 'base', hits('....X.......X...', bars, 60, [], { every: 4, pattern: '....X.......X.XX' })),
      p('hat', 'base', hits('x.x.x.x.x.x.x.x.', bars), 0.8, 0.25),
      p('crash', 'base', onBars([0, 8]), 0.8),
      // Phase 2
      p('choir', 'battle', padPart(prog, 60, 0.55)),
      p('taiko', 'battle', hits('X..X..X.X..X..X.', bars, 38), 0.8),
      p('arp', 'battle', arpPart(prog, [0, 1, 2, 3, 4, 3, 2, 1], 1, 64, 0.45), 0.65, 0.3),
    ],
  };
}

export const TRACKS: Record<TrackId, Track> = {
  pioneer2: pioneer2(),
  forest: forest(),
  caves: caves(),
  dragon: dragon(),
  derolle: derolle(),
  mines: mines(),
  warden: warden(),
};
